# Generated by Django 5.2.14 on 2026-06-02 12:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('jd_text', models.TextField()),
                ('structured_requirements', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='cvs/%Y/%m/')),
                ('parsed_text', models.TextField(blank=True, help_text='Extracted plain text the scorer reads.')),
                ('parser_version', models.CharField(blank=True, help_text='Which extractor produced parsed_text.', max_length=64)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='ats.candidate')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('criteria', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='one_active_rubric')],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scored', 'Scored'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('overall', models.FloatField(blank=True, null=True)),
                ('per_criterion', models.JSONField(default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('token_cost', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='ats.candidate')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='ats.cv')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='ats.role')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='ats.rubric')),
            ],
            options={
                'ordering': ['-overall'],
            },
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['candidate', '-uploaded_at'], name='ats_cv_candida_227471_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['role', '-overall'], name='ats_score_role_id_b57e59_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['role', 'status'], name='ats_score_role_id_240b54_idx'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('role', 'candidate', 'rubric', 'cv'), name='uniq_score_role_candidate_rubric_cv'),
        ),
    ]
