# Generated by Django 5.2.14 on 2026-06-02 13:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('questions', models.JSONField(default=list)),
                ('model_version', models.CharField(blank=True, max_length=128)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_sets', to='ats.candidate')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_sets', to='ats.cv')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_sets', to='ats.role')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('role', 'candidate'), name='uniq_screening_role_candidate')],
            },
        ),
    ]
