# Generated by Django 5.2.14 on 2026-06-03 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0005_candidateupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateupload',
            name='raw_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='candidateupload',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='ats.role'),
        ),
    ]
