# Generated by Django 5.2.14 on 2026-06-03 02:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0007_stage_pipelinecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(help_text='The developer signed (snapshot).', max_length=255)),
                ('role_title', models.CharField(blank=True, help_text='What they were placed as.', max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('client_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='PLN', max_length=8)),
                ('signed_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='ats.candidate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='ats.company')),
            ],
            options={
                'ordering': ['-signed_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DealDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='deals/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ats.deal')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, help_text='Their role at the company.', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='ats.company')),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['full_name'],
            },
        ),
    ]
