# Generated by Django 5.2.14 on 2026-06-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0008_company_deal_dealdocument_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
