# Generated by Django 5.2.14 on 2026-06-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0009_candidate_is_archived'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(fields=('role', 'name'), name='uniq_stage_role_name'),
        ),
    ]
