# Generated by Django 5.2.14 on 2026-06-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0010_stage_uniq_stage_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
