"""
Django settings for staffinit project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load a local .env if present (gitignored). Real secrets come from the
# environment in production. No .env is required to run locally — the
# defaults below point at a local Postgres `staffinit` database.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Prod MUST set DJANGO_SECRET_KEY. The insecure default is dev-only.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only-5ix1wqf4p8xxgt0gu9m52tg2eoz7j2",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() in {"1", "true", "yes"}

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]

# Railway (and most PaaS) sit behind a TLS-terminating proxy and expose the
# public hostname via an env var. Wire it in automatically so a deploy "just
# works" without hand-listing the domain.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]
_RAILWAY_DOMAIN = os.environ.get("RAILWAY_PUBLIC_DOMAIN")
if _RAILWAY_DOMAIN:
    ALLOWED_HOSTS.append(_RAILWAY_DOMAIN)
    CSRF_TRUSTED_ORIGINS.append(f"https://{_RAILWAY_DOMAIN}")

# Trust the proxy's X-Forwarded-Proto so Django knows the request is HTTPS
# (needed for CSRF, secure cookies, and redirects behind Railway's proxy).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Production hardening — only when DEBUG is off (i.e. on the deployed instance).
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Postgres-backed task queue (Lane B background scoring). Before 'ats' so it
    # initializes early and autodiscovers ats/tasks.py.
    'procrastinate.contrib.django',
    'ats',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files (admin CSS etc.) in production. Must sit
    # directly after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'staffinit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'staffinit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Postgres only — the system-of-record depends on Postgres-specific features
# (JSON fields, partial unique constraints, and the procrastinate task queue
# added in Lane B). SQLite is intentionally NOT supported.
#
# Production: point DATABASE_URL at a Postgres instance hosted in an EU region
# (e.g. Frankfurt). Candidate CVs are personal data (GDPR) — keep the data at
# rest in-region. See the design doc's GDPR section.

DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL", "postgres:///staffinit"),
        conn_max_age=600,
    )
}
# The DB MUST be UTF-8: CVs and AI rationales contain non-ASCII (accented names,
# em dashes, smart quotes). A SQL_ASCII database raises DataError on these. Force
# the test database to UTF-8 so the suite catches encoding bugs regardless of the
# local Postgres cluster's default encoding (template0 allows a non-default one).
DATABASES["default"].setdefault("TEST", {})
DATABASES["default"]["TEST"]["CHARSET"] = "UTF8"
DATABASES["default"]["TEST"]["TEMPLATE"] = "template0"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# collectstatic target (baked into the image at build); WhiteNoise serves it.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    # Manifest storage (hashed names) in production; plain storage in DEBUG so
    # runserver serves static without a collectstatic step.
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        )
    },
}

# Authentication (Lane D). Single tenant, real per-user accounts; all candidate
# PII sits behind login. No public registration — an admin provisions users.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'role_list'
LOGOUT_REDIRECT_URL = 'login'

# Uploaded CV files (raw_file on the CV model). Local dev writes under media/;
# production should use object storage in the same EU region as the database.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
